; PHP Configuration untuk Development
; File ini akan di-mount ke container untuk override default PHP settings

upload_max_filesize = 40M
post_max_size = 40M
memory_limit = 256M
max_execution_time = 300
max_input_time = 300

; Error reporting untuk development
display_errors = On
display_startup_errors = On
error_reporting = E_ALL

; Timezone
date.timezone = Asia/Makassar

; Session
session.gc_maxlifetime = 7200
session.cookie_lifetime = 7200
